### ISSUE TITLE
Fix map issues in "Definiciones y Metadatos"

### ISSUE THREAD

**Issue by felbasa** [EstadisticasPR/ViolenciaGeneroPR#36]
### Issue Description:
Remove the rendered map from the "Definitions and Metadata" section, increase the size of the map image in avp, and add it to just.

### Expected Behavior:
The rendered map should be removed, the map image in avp should be larger, and the map should be added to just.

### Actual Behavior:
The rendered map is present in "Definitions and Metadata" and the map image in avp is not the desired size.

### Task list:
- [ ] Remove rendered maps in Definiciones y Metadatos in the avp and just tabs
- [ ] Increase size of the map image in avp
- [ ] Add map image to just
