### ISSUE TITLE
Centralize data source text, data update and hyperlink to website

### ISSUE THREAD

**Issue by felbasa** [EstadisticasPR/ViolenciaGeneroPR#8]
### Issue Description:
Centralize every data source text below the centered title and hyperlink it to the appropriate website. Centralize the data update information for all tabs.

### Expected Behavior:
The source attribution should appear below the centered title and hyperlink to the specified source. Data updates should be centered horizontally.

### Actual Behavior:
The data source text is aligned to the left and does not contain any hyperlinks. Data updates are not currently centered.

### Task List:
*1. snmv*
  - [ ] Centralized data source text 
- [ ] Hyperlinked data source text 
- [ ] Centralized data update

*2. dfam*
  - [ ] Centralized data source text 
- [ ] Hyperlinked data source text 
- [ ] Centralized data update

*3. djus*
  - [ ] Centralized data source text 
- [ ] Hyperlinked data source text
- [ ] Centralized data update

*4. avp*
  - [ ] Centralized data source text 
- [ ] Hyperlinked data source text 
- [ ] Centralized data update

*5. nppr*
  - [ ] Centralized data source text 
- [ ] Hyperlinked data source text 
- [ ] Centralized data update

*6. opm*
  - [ ] Centralized data source text 
- [ ] Hyperlinked data source text 
- [ ] Centralized data update

*7. dcr*
  - [ ] Centralized data source text 
- [ ] Hyperlinked data source text 
- [ ] Centralized data update

*8. trib*
  - [ ] Centralized data source text 
- [ ] Hyperlinked data source text 
- [ ] Centralized data update

*9. caav*
  - [ ] Centralized data source text 
- [ ] Hyperlinked data source text 
- [ ] Centralized data update

**Comment by genesisperez19** [comment]
We made a different approach with this.
